Repository cmulay/python-aio, pull requests merged in 2021-05, with the labels that each got.

#8 make improvements in typing-test program
  Typing Test/README.md
  Typing Test/gensentence.py
  Typing Test/typing_test.py
Labels: documentation, enhancement, good first issue

#10 Improvement of Current Weather program.
  Current Weather/Weather.py
Labels: enhancement

#18 Added Password Generator GUI
  Password Generator GUI/pass.py
Labels: enhancement

#19 Added Message Encoder decoder
  Message Encode Decoder/encode.py
Labels: enhancement

#23 Added notepad GUI
  Notepad (GUI)/notepad.py
  Notepad (GUI)/preview.PNG
Labels: project-addition
